---
roles:
  - src: consensys.hyperledger_besu
    version: 0.3.17
  - name: consensys.goquorum
    src: https://github.com/ConsenSys/ansible-role-goquorum
    version: master
  - name: cloudalchemy.node_exporter
    version: 2.0.0
  - name: consensys.web3signer
    version: v1.0.4

collections:
  - name: amazon.aws
    version: 3.5.0
  - name: community.aws
    version: 3.6.0
